const ErrorCodes = {
  INVALID_INPUT: 1,
  EXTERNAL_SERVICE_ERROR: 2,
  NOT_FOUND: 3,
  DATABASE_ERROR: 4,
  INVALID_CSV_DATA_COLUMN: 6,
  INVALID_CSV_DATA_FORMAT: 5,
  MALFORMED_JSON_ERROR_CODE: 88,
  RUNTIME_ERROR_CODE: 99,
  UNEXPECTED_ERROR: 100
}

export default ErrorCodes;
